### ISSUE TITLE
Where to download pre-trained models?

### ISSUE THREAD

**Issue by xiekunwhy** [IOB-Muenster/TEclass2#1]
Hi,

Teclass2 paper says that authors have trained a model using dfam and repbase informations. Where can we download the training results?

Best
Kun

**Comment by IOB-Muenster** [comment]
Hi,
The pre-trained models can be downloaded from here:
https://www.bioinformatics.uni-muenster.de/share/TEclass2/model/?lang=en

Best,

-Matias


xiekunwhy schrieb am 2023-10-20:
